spring:
  application:
    name: ${SPRING_APP_NAME:simple-spring-security-project}

logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %cyan(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
     springframework:
       security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
    

