spring:
  config:
    activate:
      on-profile: prod

  application:
    name: ${SPRING_APP_NAME:simple-spring-security-project}

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3307}/${DATABASE_NAME:demo-spring-sec}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}

logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %cyan(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:ERROR}

server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:10m}